### ISSUE TITLE
plss provide me the dataset 

### ISSUE THREAD

**Issue by karthick8529** [NemesLaszlo/Sentiment-Analysis-and-Stock-Values#1]

**Comment by NemesLaszlo** [comment]
Every notebook from the repository contains the dataset builder codeblocks, with that you can easily create fresh datasets to run your analyses.

Unfortunately, I cannot provide the older dataset what i used, but as i mentioned, you can create your own fresh datasets with the code blocks from the first part of the notebooks. Also, you are able to change which companies's data to be used for this scraping process.
